FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN python db/seed.py
EXPOSE 8000 8001 8002

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]